language: python
python:
    - 3.6
notifications:
  email: false
 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
  - pip install atlas numpy scipy matplotlib nose python-dateutil pandas statsmodels
  - pip install https://bitbucket.org/dalcinl/igakit/get/default.tar.gz
  - pip install coveralls
  - ./setup.sh
 
# Run test
script:
  - nosetests --with-coverage --cover-package=interfaces --cover-package=utilities tests
 
# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
